#!/bin/bash -l



#$ -S /bin/bash
#$ -l h_rt=12:0:0 
#$ -l mem=20G
#$ -pe smp 1
#$ -N RICHARD
#$ -wd /home/regmond/Scratch/richard_CLAPAnalysis/2_bam_to_bw


## qsub -t 1-20 3_bamcompare.qsub


module load blic-modules
module load deeptools/3.5.5


number=$SGE_TASK_ID
paramfile="/home/regmond/Scratch/richard_CLAPAnalysis/2_bam_to_bw/samples_paired.txt"

sample=`sed -n ${number}p $paramfile | awk '{print $1}'`
input=`sed -n ${number}p $paramfile | awk '{print $2}'`


hs_effectivegenomesize=2805636231
mm_effectivegenomesize=2467481008
mixed_effectivegenomesize=5273117239

for type in "" "_withdups";do
	bamCompare --bamfile1 CLAPAnalysis_output${type}_repsMerged/${sample}.merged.mapped.bam \
		--bamfile2 CLAPAnalysis_output${type}_repsMerged/${input}.merged.mapped.bam \
		-o CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.inputnormalised.bg \
		--outFileFormat bedgraph \
		--binSize 100 \
		--normalizeUsing CPM --scaleFactorsMethod None \
		--effectiveGenomeSize $mixed_effectivegenomesize \
		--ignoreForNormalization chrX chrY \
		--extendReads \
		--operation ratio \
		--pseudocount 0 1 \
		--skipZeroOverZero
		
	#- get the human data (only canonical chrs, no repeats either)
	awk '$1 ~ /^chr([1-9]_human$|1[0-9]_human$|2[0-2]_human$|X_human$|Y_human$)/' CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.inputnormalised.bg > CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.hs.inputnormalised.bg
	#- remove the trailing "_human"
	perl -p -i -e 's/_human//g' CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.hs.inputnormalised.bg
	#- get bedgraph to bigwig
	bedGraphToBigWig CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.hs.inputnormalised.bg hg38.chrom.sizes CLAPAnalysis_output${type}_repsMerged/bigwigs/${sample}.merged.mapped.hs.inputnormalised.bw
	
	#- get the mouse data (only canonical chrs, no repeats either)
	awk '$1 ~ /^chr([1-9]_mouse$|1[0-9]_mouse$|X_mouse$|Y_mouse$)/' CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.inputnormalised.bg > CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.mm.inputnormalised.bg
	#- remove the trailing "_mouse"
	perl -p -i -e 's/_mouse//g' CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.mm.inputnormalised.bg
	#- get bedgraph to bigwig
	bedGraphToBigWig CLAPAnalysis_output${type}_repsMerged/bedgraphs/${sample}.merged.mapped.mm.inputnormalised.bg mm10.chrom.sizes CLAPAnalysis_output${type}_repsMerged/bigwigs/${sample}.merged.mapped.mm.inputnormalised.bw
done

